stages:
  - syntax
  - publish
  - deploy


flake8:
  image: ejplatform/python:alpine
  stage: syntax
  script:
    - flake8


build docker:
  image : docker
  stage: publish
  services:
    - docker:dind
  script:
    - docker build . -t pablodiegoss/workshop:latest
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push pablodiegoss/workshop:latest


deploy to rancher:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
    - "upgrade
            --service django
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --rancher-key $RANCHER_ACCESS_KEY
            --rancher-secret $RANCHER_SECRET_KEY
            --rancher-url $RANCHER_URL"