stages:
  - test
  - publish
  - deploy

flake8:
  stage: test
  image: ejplatform/python:alpine
  scripts:
    - flake8

push docker:
  stage: publish
  image: docker
  services:
    - docker:dind
  script:
    - docker build . -t lappisworkshop/devops:latest
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
    - docker push lappisworkshop/devops:latest

deploy to rancher:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    -"upgrade 
        --service django
        --stack $RANCHER_STACK
        --rancher-url $RANCHER_URL
        --rancher-key $RANCHER_ACCESS_KEY
        --rancher-secret $RANCHER_SECRET_KEY
        --environment $RANCHER_ENVIRONMENT
    "