stages:
  - stylesheet
  - test
  - publish
  - deploy

variables:
  TEMP_IMAGE_NAME: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_SHORT_SHA

#### Style Check Tests ####
.run stylecheck:
  image: python:3.8-buster
  stage: stylesheet
  before_script:
    - cd src/

run black check:
  extends: .run stylecheck
  script:
    - pip install black==21.4b1
    - black --check .

run isort check:
  extends: .run stylecheck
  script:
    - pip install isort==5.8.*
    - isort --check-only --skip migrations  --profile black .

build docker:
  image : docker
  stage: publish
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $TEMP_IMAGE_NAME .
    - docker push $TEMP_IMAGE_NAME


